### ISSUE TITLE
Authorization Header not forwarding?

### ISSUE THREAD

**Issue by y0shi** [Droplr/serverless-api-cloudfront#11]
I'm using serverless-api-cloudfront to front my api-gateway and lambda function.  However, it doesn't seem that the Authorization header is being forwarded, so I can't use an authorizer function.  After the deploy, if I call the api-gw endpoint directly, the Authorization header gets through, but if I call it via cloudfront, I get an unauthorized repsonse and there's no header on that call.  If I go into the cloudfront manually and change the cache control to forward the header, it will begin to work.  After a manual edit, the important part of the cloudfront json looks like this:

``` json
"DefaultCacheBehavior": {
                "TargetOriginId": "ApiGateway",
                "ForwardedValues": {
                    "QueryString": true,
                    "Cookies": {
                        "Forward": "all"
                    },
                    "Headers": {
                        "Quantity": 1,
                        "Items": [
                            "Authorization"
                        ]
                    },
                    "QueryStringCacheKeys": {
                        "Quantity": 0
                    }
                },
```

But when I deploy via serverless, it always looks like this:
``` json
"DefaultCacheBehavior": {
                "TargetOriginId": "ApiGateway",
                "ForwardedValues": {
                    "QueryString": true,
                    "Cookies": {
                        "Forward": "all"
                    },
                    "Headers": {
                        "Quantity": 0
                    },
                    "QueryStringCacheKeys": {
                        "Quantity": 0
                    }
                },
```

That matches what is in `cloudformation-template-update-stack.json` in the .serveless directory.  I tried changing the serverless yaml file to add the header forwarding with this: 
``` yaml
plugins:
  - serverless-api-cloudfront

  apiCloudFront:
    defaultCacheBehavior:
      forwardedValues:
        headers:
          quantity: 1
          items:
            - Authorization
```

But that doesn't seem to have any effect.  Am I doing something wrong?  Is there a way to get the Authorization header forwarded?

**Comment by orfin** [comment]
Hi! Indeed, by default no headers are being forwarded to the origin server, so it Authorization header won't be visible.
However, I've just merged PR of @DanielMuller that added possibility to configure a list of headers that should be forwarded: https://github.com/Droplr/serverless-api-cloudfront/pull/9

That will allow you to add "Authorization" to the "headers" configuration. Let me know if that worked for you! 

Thanks, Antoni

**Comment by orfin** [comment]
For now I'm closing this issue, if #9 won't work for you, let me know and we will reopen it :-) Thanks
