### ISSUE TITLE
Parameters for PriceClass and MinimumProtocolVersion would be nice

### ISSUE THREAD

**Issue by janvanzoggel** [Droplr/serverless-api-cloudfront#13]
The plugin uses fixed / default Price Class "Use All Edge Locations (Best Performance)" and Security Policy "TLSv1". Would be nice if you could configure these as well through parameters like (for example):

DistributionConfig
  PriceClass: PriceClass_100

DistributionConfig
  ViewerCertificate:
    MinimumProtocolVersion: TLSv1.1_2016

**Comment by Necromos** [comment]
Hey there!

As found out here: https://github.com/Droplr/serverless-api-cloudfront/pull/14 PriceClass can be configured in plugin :) I will close this PR soon.

About Security Policy, any PR is welcome :)

**Comment by Necromos** [comment]
Published under 0.9.5 :)
