### ISSUE TITLE
Allow security policy to be configurable in the CloudFront Distribution

### ISSUE THREAD

**Issue by skyzyx** [Droplr/serverless-api-cloudfront#16]
I would love to be able to mandate TLS 1.2+ connections exclusively for my distribution. It would be wonderful if this were configurable via this plugin.

**Note:** This is different from #17.

See:

* [MinimumProtocolVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-viewercertificate.html)

**Comment by Necromos** [comment]
https://github.com/Droplr/serverless-api-cloudfront/pull/25

**Comment by Necromos** [comment]
Added under 0.9.5 :)
