### ISSUE TITLE
Specify which additional IAM Policys are needed

### ISSUE THREAD

**Issue by adambrgmn** [Droplr/serverless-api-cloudfront#22]
Hi, thanks for this plugin! Just what I need in order to build an image resizing
service to avoid invoking Lambdas on every request.

But I've run into an issue where my default IAM role didn't have permission to
create and list the resources necessary for this plugin.

So far I've used simple trial and error and determined four policys that needs
to be attatched to the the IAM role:

- `cloudfront:CreateDistribution`
- `cloudfront:GetDistribution`
- `cloudfront:UpdateDistribution`
- `cloudfront:DeleteDistribution`
- `cloudfront:TagResource`

And that's compared to the policy statements [recommended by Serverless][docs],
found [in this gist][gist].

Maybe it should just be mentioned somewhere in the README.md and I'll be happy
to provide a PR.

[docs]:
  https://serverless.com/framework/docs/providers/aws/guide/credentials#creating-aws-access-keys
[gist]: https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8

**Comment by Necromos** [comment]
Hey! That sounds great!

If you are interested in preparing a PR, feel free to do so :)

If not, then I will add it to personal TODOs :)

**Comment by adambrgmn** [comment]
I'd be happy to provide a PR. I'll get it up tomorrow (European time here 😬).
