### ISSUE TITLE
Cognito-secured API returns 401 from custom domain

### ISSUE THREAD

**Issue by dpwhittaker** [Droplr/serverless-api-cloudfront#4]
I used this to create a cloudfront distribution for my api, then pointed my custom domain at the cloudfront distribution.  I can PostMan to my api gateway url just fine, passing a valid Authorization header, but when I attempt to go through the custom domain, it always returns a 401 error.  Any idea what might be going on here?  Are there some settings I'm missing to allow the Authorization header through or something?

**Comment by Necromos** [comment]
Hey!
You need to forward Authorization header actually, please take a look at: https://github.com/Droplr/serverless-api-cloudfront/issues/15

Hope it helps!
